[package]
name = "synthy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
vst = "0.3"
fundsp = "0.3.1"
num-derive = "0.3"
num-traits = "0.2"
wmidi = "4"